openapi: 3.0.0
info:
  title: Liedjes Selectie API
  description: API voor het beheren van christelijke liederen en liedkeuzes.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Development server
tags:
  - name: songs
    description: Liederen
paths:

  /songs:
    get:
      summary: "Beschikbare liederen ophalen"
      description: "Retourneer een lijst van beschikbare liederen die gebruikers kunnen selecteren."
      responses:
        '200':
          description: "Succesvol opgehaald"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      example: "Amazing Grace"
                    number:
                      type: integer
                      example: 101
                    bundel:
                      type: string
                      example: "Opwekkingsliederen"
        '500':
          description: "Interne serverfout"

  /dates:
    get:
      summary: "Beschikbare datums ophalen"
      description: "Retourneer een lijst van datums waarvoor liederen kunnen worden gekozen."
      responses:
        '200':
          description: "Lijst van datums succesvol opgehaald"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "2024-10-03"
        '500':
          description: "Interne serverfout"

  /submit-songs:
    post:
      summary: "Liedkeuzes voor een datum indienen"
      description: "Stuur de gekozen liederen en een motivatie voor een bepaalde datum naar de server."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                  example: "2024-10-03"
                songs:
                  type: array
                  items:
                    type: string
                  example: ["Amazing Grace", "Blessed Assurance", "Eigen suggestie lied"]
                motivation:
                  type: string
                  example: "We kozen deze liederen omdat ze perfect passen bij het thema van de zondag."
      responses:
        '200':
          description: "Liedkeuzes succesvol ingediend"
        '400':
          description: "Ongeldige invoer"
        '500':
          description: "Interne serverfout"

